Add / GhostCMS Migrator
Automattic/newspack-migration-tools pull request #5
Opened 2024-07-24 22:25 UTC by ronchambers

## GhostCMS Migrator copied from Newspack Custom Content Migrator

The primary logic that migrates a GhostCMS JSON file was unchanged from Newspack Custom Content Migrator, but what did change was:

* A [documentation file](https://github.com/Automattic/newspack-migration-tools/blob/f0c6bd603e6590c4bf11a4b80a2f34e7dcc55e87/docs/GhostCMS.md) was added to the `docs/` folder.
* The migrator was divided into a Migrator file and a Helper file.
* The migrator was added to the list of `cli_commands`.
* The way the Migrator/Helper logs to files and cli was updated. 
* Tests were added along with a [json fixture file](https://github.com/Automattic/newspack-migration-tools/blob/f0c6bd603e6590c4bf11a4b80a2f34e7dcc55e87/tests/fixtures/ghostcms.json).

## How to run:

```
wp newspack-migration-tools ghostcms-import --json-file=ghostcms.json --ghost-url=https://newspack.com/ --default-user-id=1
```

## Fatal Conflicts:

If the Newspack Plugin is also active, and the following error has encountered:

```
Error: CoAuthorsPlusHelper construct threw exception: CoAuthors Plus is not installed or active. --> /newspack-repos/newspack-custom-content-migrator/dev/newspack-migration-tools/src/Logic/GhostCMSHelper.php:500
```

Please do [this fix](https://github.com/Automattic/newspack-migration-tools/issues/41):

`wp config set NEWSPACK_ENABLE_CAP_GUEST_AUTHORS true --raw --type=constant`

2024-08-15 06:19 UTC, ronchambers reviewed
I've itemized each piece of the PR here in this review.  Please reply or mark each "resolve conversation" as you see fit.

2025-01-06 10:39 UTC, naxoc requested changes
Added a couple of requests, but this should be good to go once we test that the code still works with the recent changes in the NMT.

2025-01-06 10:39 UTC, naxoc commented on tests/Command/TestGhostCMSMigrator.php
> +	public function test_cmd_ghostcms_import() {
Would it be possible to test smaller units than the entire import?

The GhostHelper does most of the heavy lifting, I don't think GhostCMSMigrator needs a test at all. What do you think?

2025-01-06 10:39 UTC, naxoc commented on src/Logic/GhostCMSHelper.php
> +	private function log( string $message, string $level = 'info', bool $exit_on_error = false ): void {
This function should not be necessary anymore. Logging supports multilogging and other tricks now: https://github.com/Automattic/newspack-migration-tools/blob/trunk/docs/logging.md

2025-01-07 03:40 UTC, ronchambers commented on tests/Command/TestGhostCMSMigrator.php
> +	public function test_cmd_ghostcms_import() {
Removed.  If/when we get the next GhostCMS migration we can/should discuss breaking the command into smaller test-able chunks...

2025-01-07 03:42 UTC, ronchambers commented on src/Logic/GhostCMSHelper.php
> +	private function log( string $message, string $level = 'info', bool $exit_on_error = false ): void {
I left the function...but updated all the logging based on the link you shared above, and the "patch" file you had sent me back in November.

2025-01-13 12:21 UTC, naxoc approved these changes
Yes! Let's merge this. Thank you Ron 🙏

2025-01-15 05:08 UTC, merged